[project]
name = "core-backend"
version = "0.1.0"
description = "The Navi4All Core Backend API"
readme = "README.md"
requires-python = ">=3.11.12"
dependencies = [
    "fastapi[standard]>=0.116.1",
]
